services:
  - type: web
    name: securin-recipes
    env: java
    plan: free
    region: oregon
    rootDir: .
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/recipes-0.0.1.jar
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: securin-db
        property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: securin-db
        property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: securin-db
        property: password
databases:
  - name: securin-db
    plan: free

