spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securin
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: ${PORT:8080}
